CAUTION: **Under construction**

= cmdlnParser

**cmdlnParser** is a tool to make command-line-parameter processing convinient for Nim!

== Features

The concept of this tool is to simplify bothersome command-line-prameter setting, checking and processing.

=== 1. simple setting

By creating parameter setting object, you can complete to define what parameters this program has and how to process each parameters.

* flexible parameter setting
** you just ok to code default value or processing procesure
** you can create original parameter format
*** support `prefix` and `separator` format according to " `{prefix}{keyword}{separator}{input}`
*** ex: `--path:input` " , `/p input` etc.
* automatic detection of types
** judge parameter type as string if you set only parameter keyword
** you do not have to specify any generics type like `...[type](...)`
** including original types (but must code procesure of converting)
* function attentive to needs
** support various parameter patterns
*** no prefix parameter (like `name.exe param1 param2 ...`)
+
WARNING: in this case, type checking is done in the order in which they are set.

*** no separator parameter (like `-n50`)
** each parameter can have default value
*** you can select that parameter has default value or not
** multiple parameter keyword
*** you can let defferent parameter keywords have the same meaning
** return value linking
*** you can arrange final output values by setting relationship between keyword and output
** each parameter has own description
*** you can see the help documentation by inputting parameter like `-h`

> now is on the way...

=== 2. wrap troublesome work

To process command-line-parameters, you just call `parse` procesure with setting object.

* wrap various checking
** check number of parameters
** check type of parameters
* return arranged tuple
** by linking parameter keyword and return value (by settings), returns arranged tuple
*** it means that the returned values do not set in the order they are located in calling procedure but do set in order by link settings

== Sample

If you let your program process with some command-line-parameters, try this tool with simple steps.

> In this case, it is considerd that you will create a program to search the target directory.

=== step1
You need to design what parameters you need, like example below:

--path: ::
This defines target path.
+
[options="header" cols="1,>1"]
|====
^|setting name ^|value
|type|string
|parse proc|nothing
|default|nothing
|specific options|nothing
|====

--search: ::
This defines search strings, +
and this keyword will be able to be set any number.
+
[options="header" cols="1,>1"]
|====
^|setting name ^|value
|type|string
|parse proc|nothing
|default|nothing
|specific options|multiple parameters permitted
|====

--keyword: ::
This is an alias of search option.
+
[options="header" cols="1,>1"]
|====
^|setting name ^|value
|type|string
|parse proc|nothing
|default|nothing
|specific options|multiple parameters permitted
|====

--regex: ::
This defines to use regex or not. +
and this option must be defined only once.
+
[options="header" cols="1,>1"]
|====
^|setting name ^|value
|type|bool
|parse proc|nothing
|default|false
|specific options|multiple parameters banned
|====

=== step2
Commit your design by creating object of `CmdParam` object using `newCmdParam` procedure. +

CAUTION: object must be defined as `ver` definition.

[source, nim]
----
var cmdParser = newCmdParser(
  newCmdParam("path", options=BAN_MULTIPLE),
  newCmdParam("search"),
  newCmdParam("keyword"),
  newCmdParam("regex", false, options=BAN_MULTIPLE)
)
----

=== step3
Define relationship between options and result values. +
In this case, `search` option and `keyword` option should be returned as the same reuslt value. +
Also, the order of result values can be defined at the same time.
[options="header" cols="1,>1"]
|====
^|order ^|keyword
|first|path
|second|search, keyword
|third|regex
|====
So, update the object created in step 2 in order to add the `results` option, as below:
[source, nim]
----
var cmdParser = newCmdParser(
  results=("path",["search","keyword"],"regex"),
  newCmdParam("path", options=BAN_MULTIPLE),
  newCmdParam("search"),
  newCmdParam("keyword"),
  newCmdParam("regex", false, options=BAN_MULTIPLE)
)
----
NOTE: `prefix` and `separator` can be also defined at this `newCmdParser` procedure (`pre` option and `sep` option).

=== step4
Call `parse` procedure which `CmdParser` object has (as correctly, set it as the first argument). +
And set command-line-parameters you want to parse at second argument.
[source, nim]
----
let cmdlineParams = os.getCommandlineParams()
let res = cmdParser.parse(cmdlineParams)
----

=== step5
If you come here, the parsing result should be assigned to the `res` variable. +
For example, if command-line-params are +
`["--path:/var","--search:test","--keyword:test2","--regex:true"]` , +
you can see +
`("/var", @["test","test2"], true)`.

=== overall code of this sample

[source, nim]
----
import os
import cmdlnparser

var cmdParser = newCmdParser(
  results=("path",["search","keyword"],"regex"),
  newCmdParam("path", options=BAN_MULTIPLE),
  newCmdParam("search"),
  newCmdParam("regex", false, options=BAN_MULTIPLE)
)
let cmdlineParams = os.getCommandlineParams()
let res = cmdParser.parse(cmdlineParams)
----


== Non-standard required library

nothing for now

== TODO

* [ ] improve type estimation
* [x] corresponds to boolean type